### ISSUE TITLE
[FEATURE] Design Dataset Search Results Layout

### ISSUE THREAD

**Issue by JohananOppongAmoateng** [Vetdatahub/VetDataHub_Website#26]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

 Design a clean and easily navigable layout for displaying search results, with filters and sorting options.

### Proposed Solution

 Design a clean and easily navigable layout for displaying search results, with filters and sorting options.

### Do you want to work on this issue?

No

**Comment by Ezi-code** [comment]
Just a few concerns about this issue:
- Will the person implementing this be the same person to setup the views and routes for creating data?
- And also, I think this would be more comprehensive if we understand the format the data is needed in. From the look of things, the website has an `API` section of it. Will this be for the `API` or be rendered to a html template?
