### ISSUE TITLE
Add a linting and formatting workflow

### ISSUE THREAD

**Issue by JohananOppongAmoateng** [Vetdatahub/VetDataHub_Website#3]

**Comment by ravinder-chadha** [comment]
Hey @JohananOppongAmoateng,
I would like to write this workflow for you, kindly assign me this.

**Comment by ravinder-chadha** [comment]
Also it would be great if you can describe a more about what all you need in the PR to resolve this issue.

**Comment by JohananOppongAmoateng** [comment]
@ravinder-chadha Sorry someone already submitted a pr for this. Thank you
