### ISSUE TITLE
[FEATURE]  Dataset Upload System

### ISSUE THREAD

**Issue by JohananOppongAmoateng** [Vetdatahub/VetDataHub_Website#6]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

 Implement a system that allows users to upload datasets. The system should support large file uploads and provide feedback on the progress.

### Proposed Solution

 Implement a system that allows users to upload datasets. The system should support large file uploads and provide feedback on the progress.

### Do you want to work on this issue?

No

**Comment by Rani1303** [comment]
Hey! I would like to work on this issue.

**Comment by JohananOppongAmoateng** [comment]
@Rani1303  are you still working on this?
